# Generated by Django 3.1.4 on 2020-12-03 08:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'El nombre debe contener al menos 2 caracteres')])),
                ('apellido', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'El apellido debe contener al menos 2 caracteres')])),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProfesionalMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'El nombre debe contener al menos 2 caracteres')])),
                ('apellido', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'El apellido debe contener al menos 2 caracteres')])),
                ('especialidad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente')),
                ('profesional_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.profesionalmedico')),
            ],
        ),
    ]
