# Generated by Django 3.1.4 on 2020-12-03 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_auto_20201203_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='historial_medico',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='clinica.historialmedico'),
        ),
    ]
