# Generated by Django 3.1.4 on 2020-12-11 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinica', '0006_auto_20201209_2144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.AddField(
            model_name='profesionalmedico',
            name='medico',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
