# Generated by Django 3.1.4 on 2020-12-11 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinica', '0007_auto_20201211_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='profesional_medico',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Profesional Medico'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
