# Generated by Django 3.1.4 on 2020-12-11 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinica', '0008_auto_20201211_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesionalmedico',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='profesionalmedico',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='profesionalmedico',
            name='pacientes',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='profesionales_medicos',
        ),
        migrations.AlterField(
            model_name='turno',
            name='profesional_medico',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Personal Medico'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Cabecera',
        ),
        migrations.DeleteModel(
            name='Especialidades',
        ),
        migrations.DeleteModel(
            name='ProfesionalMedico',
        ),
    ]
