# Generated by Django 3.1.4 on 2021-01-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0012_auto_20201213_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='localidad',
            field=models.CharField(default='CABA', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=11),
        ),
    ]
